version: 2.1

commands:
  pipelineid:
    description: prints the pipeline id
    parameters:
      to:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file :
          requires:
            - save_hello_world_output
      - print_workflow_id
      - fail

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 'echo "hello world" > ~/output.txt'
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: cat output.txt
          command: 'cat ~/output.txt'

  print_workflow_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - pipelineid:
          to: &defualt
  
  fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: return 1
      - run:
          command: echo Test Failed
          when: on_fail 

